### ISSUE TITLE
Works on RTX 3080 (mobile)

### ISSUE THREAD

**Issue by fat-tire** [nkolkin13/NeuralNeighborStyleTransfer#2]
Just wanted to report this works on a RTX 3080 mobile.

Tested yesterday on Ubuntu 20.04.4 LTS w NVIDIA Driver Version: 510.54  & CUDA Version: 11.6, plus: 

Python 3.8.10
PyTorch (torch) 1.11.0+cu113
torchvision 0.12.0+cu113
Imageio 2.16.1
Numpy 1.22.3

To install dependencies, I used:

` pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113`

Everything worked fine.

This is cool af BTW

![github-s3](https://user-images.githubusercontent.com/528174/160259674-27eeb329-10f1-4b6b-8bc5-aab786d5c53a.jpg)
![github-s5](https://user-images.githubusercontent.com/528174/160259704-e0b9e67a-eeb1-422f-b65b-6770a01c6f4c.jpg)

**Comment by nkolkin13** [comment]
Hi! Thank you for trying it out and reporting that it works on RTX 3080 mobile! 
(and glad you enjoyed using it :) )
