### ISSUE TITLE
Question on Inference performance

### ISSUE THREAD

**Issue by vanga** [nkolkin13/NeuralNeighborStyleTransfer#9]
Hi,

I see that it is taking around 10s on A100 to generate a 512 stylyzed image (Without knowing the technical details of the architecture, I would imagine the style transfer to be faster than generating images from scratch using the models like GANs or text-2-img models which can generate new images in a couple of seconds or even less, I apologize if this is less informed comment from me).

I am just curious if there is anything that can be warmed up or tweaked to make the inference time in the order of a couple of seconds? I see that VGG model gets loaded every time.. but that's inconsequential compared to the overall time. Is there anything that can be warmed up or tweaked to improve the performance?

Thanks.

**Comment by nkolkin13** [comment]
Hi Vanga,
This is an optimization based method, so there isn't a specialized neural network that does the stylization; instead the output image is iteratively updated to minimize the objective function (which is based on features extracted by VGG). This is inherently much slower than the forward pass of a neural network. You can play with reducing the number of iterations, but it will make results worse.
Best,
Nick
